Project-local-setting?

1. Do: pip freeze > FILE_NAME.txt to get the required libraries and packages
2. Debug any issues!
3. The problem will occur as most libraries and packages get updated without official announce. What to do here?

=> my case the problem was
```
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x104b52730>
Traceback (most recent call last):
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/site-packages/pandas/__init__.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
ImportError: numpy.core.multiarray failed to import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ascent/PycharmProjects/lm-backend/lm_backend/urls.py", line 24, in <module>
    from account.views import CompanyAccountViewSet, CompanyView, ProfileView, \
  File "/Users/ascent/PycharmProjects/lm-backend/account/views.py", line 12, in <module>
    import pandas as pd
  File "/Users/ascent/.pyenv/versions/backendpy/lib/python3.6/site-packages/pandas/__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: umpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.

```

1. C extension problem?
2. module compiled against API version 0xc but this version of numpy is 0xa. => updated version of numpy
3. scikitlearn from 0.19 => 0.20

** scikit-learn requires, python(>=3.4), Numpy(>= 1.8.2), SciPy(>=0.13.3)

The error seems to run in a cycle. So decided to install python version 3.5.2 instead.
